### ISSUE TITLE
Incompatible with 2021.3

### ISSUE THREAD

**Issue by Leo40Git** [Earthcomputer/class-file-indexer#3]
![image](https://user-images.githubusercontent.com/7997354/144589268-68753974-f078-48f4-a122-f1e32f632d3b.png)
Seems like it's fixed here already, but there's no release with the new version bounds.

**Comment by Earthcomputer** [comment]
I know, I'm trying to get through jetbrains' approval process

**Comment by Leo40Git** [comment]
Ah, alright 👍

**Comment by Earthcomputer** [comment]
It's been approved now
